### ISSUE TITLE
It does not work although everything looks ok.

### ISSUE THREAD

**Issue by Yang-Siyuan** [adafruit/Adafruit_CircuitPython_PCA9685#44]
It doesn't work on my device, Raspberry Pi 4B. Everything looks OK, no errors, no warnings, but nothing happened, the PWM light is not blinking, it seems like there is no message sent to pca9685.

**Comment by ladyada** [comment]
hi if there's no python errors its probably a wiring issue. best place to post is in the forums or tech support of the place you purchased the Pi and PWM driver board!
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)
